### ISSUE TITLE
I am receiving these errors

### ISSUE THREAD

**Issue by pandey623** [insthync/rpg-php-service#1]
I followed all the steps for PHP web services integration

[GET->Error] service-time Cannot connect to destination host 
UnityEngine.Debug:LogError(Object)
<GetRoutine>d__7:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:100)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[POST->Error] validate-login-token Cannot connect to destination host 
UnityEngine.Debug:LogError(Object)
<PostRoutine>d__10:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:174)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[POST->Error] register Cannot connect to destination host 
UnityEngine.Debug:LogError(Object)
<PostRoutine>d__10:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:174)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

and in page : http://www.busygamers.com/rpg-php-service-master/index.php
<!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>Only variables should be passed by reference</p>
<pre>[rpg-php-service-master/fatfree/lib/base.php:2342] Base->error()
[rpg-php-service-master/index.php:315] Base->{closure}()
</pre>
</body>
</html>

**Comment by insthync** [comment]
Did you set `serviceUrl` in `WebServiceClient` component correctly?

**Comment by pandey623** [comment]
I added http://www.busygamers.com/rpg-php-service-master/ in serviceUrl in WebServiceClient component 
Now I am getting this error

[GET->Error] service-time HTTP/1.1 500 Internal Server Error <!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>Only variables should be passed by reference</p>
<pre>[rpg-php-service-master/fatfree/lib/base.php:2342] Base->error()
[rpg-php-service-master/index.php:315] Base->{closure}()
</pre>
</body>
</html>
UnityEngine.Debug:LogError (object)
WebServiceClient/<GetRoutine>d__7:MoveNext () (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:100)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by pandey623** [comment]
I am waiting for your response

**Comment by insthync** [comment]
Try delete codes in index.php
```
$it = new RecursiveDirectoryIterator("./extensions");
foreach(new RecursiveIteratorIterator($it) as $file) {
    if (in_array(strtolower(array_pop(explode('.', $file))), array('php'))) {
        include $file;
    }
}
```
line 314-319

**Comment by pandey623** [comment]
![image](https://user-images.githubusercontent.com/25692596/118491819-fe760400-b73c-11eb-9ecf-9891a71149c7.png)
![image](https://user-images.githubusercontent.com/25692596/118491959-236a7700-b73d-11eb-841a-0ca74d0b4b93.png)

I have commented the code in index.php but still, I am getting the error. please help.

**Comment by insthync** [comment]
Use URL: http://busygamers.com/rpg-php-service-master/

**Comment by pandey623** [comment]
I Updated http://busygamers.com/rpg-php-service-master/ in serviceUrl in WebServiceClient component

Now I am getting this error in Unity Editor:

[GET->Error] service-time HTTP/1.1 404 Not Found <!DOCTYPE html>
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>Not Found</h1>
<p>HTTP 404 (GET //service-time)</p>
<pre>[rpg-php-service-master/fatfree/lib/base.php:1787] Base->error()
[rpg-php-service-master/index.php:584] Base->run()
</pre>
</body>
</html>
UnityEngine.Debug:LogError (object)
WebServiceClient/<GetRoutine>d__7:MoveNext () (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:100)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)


![image](https://user-images.githubusercontent.com/25692596/118505724-4ea79300-b74a-11eb-921e-d954e65b8a0f.png)
![image](https://user-images.githubusercontent.com/25692596/118505865-70087f00-b74a-11eb-8921-e7d5cce71aca.png)

**Comment by dclgamingtr** [comment]
![Adsız](https://user-images.githubusercontent.com/61230304/118507338-d08dc100-b736-11eb-83f5-2da86fdc16ec.png)
Delete this at the end man. '' / ''

**Comment by dclgamingtr** [comment]
And I suggest you encrypt your config file. It can be seen by everyone now. 

http://busygamers.com/rpg-php-service-master/configs/config.ini

**Comment by pandey623** [comment]
Now I am getting this error
And can you guide me on how to encrypt config.ini page?
![image](https://user-images.githubusercontent.com/25692596/118508820-24a3a000-b74d-11eb-9cdc-40d542c8bce5.png)
![image](https://user-images.githubusercontent.com/25692596/118508858-3127f880-b74d-11eb-8d18-90d49d1328d6.png)
![image](https://user-images.githubusercontent.com/25692596/118508988-4c930380-b74d-11eb-9717-32adb8096042.png)

**Comment by dclgamingtr** [comment]
Change the name to Config.php instead of config.ini. 

<?php 
[globals]

# Debug mode 0 for production and 3 for development
DEBUG=3

# Database settings
db_prefix=rpg_
db_host=localhost
db_port=3306
db_name= Db Name
db_user= username
db_pass=pass

# FALSE for Development mode and TRUE for Production mode
db_freeze=FALSE

# Timezone
timezone=Asia/Jakarta

# Security key
jwt_secret=jwtSecret1234

# Apple Appstore
appstore_is_sandbox=TRUE

# Google Play
play_public_key=

# Request action by request query
use_request_query_action=FALSE

# Raid boss rewarding delay (Default is 300 seconds or 5 minutes)
raid_boss_rewarding_delay=300
 ?>

**Comment by pandey623** [comment]
> Change the name to Config.php instead of config.ini.

Where?

**Comment by pandey623** [comment]
> Now I am getting this error
> And can you guide me on how to encrypt config.ini page?
> ![image](https://user-images.githubusercontent.com/25692596/118508820-24a3a000-b74d-11eb-9cdc-40d542c8bce5.png)
> ![image](https://user-images.githubusercontent.com/25692596/118508858-3127f880-b74d-11eb-8d18-90d49d1328d6.png)
> ![image](https://user-images.githubusercontent.com/25692596/118508988-4c930380-b74d-11eb-9717-32adb8096042.png)

Please look into this error as well

**Comment by dclgamingtr** [comment]
You can use it to prevent buddy data from being visible. :)


[config.zip](https://github.com/insthync/rpg-php-service/files/6494699/config.zip)

**Comment by dclgamingtr** [comment]
// Read configs
$f3->config('configs/config.php');

İndex.php line 13 change it :)

**Comment by pandey623** [comment]
> You can use it to prevent buddy data from being visible. :)
> 
> [config.zip](https://github.com/insthync/rpg-php-service/files/6494699/config.zip)

I have to replace this file (which you shared) with file in my server right?
Do I have to change the file name from config.ini to Config.php?
I have to change this
// Read configs
$f3->config('configs/config.ini');

to this 

// Read configs
$f3->config('configs/config.php');


?

**Comment by dclgamingtr** [comment]
Yes edit the config.php according to your own. Just delete the config.ini file. Likewise, just fix the part in index.php as php.

**Comment by pandey623** [comment]
![image](https://user-images.githubusercontent.com/25692596/118511192-4b62d600-b74f-11eb-99f7-8814b763101b.png)
![image](https://user-images.githubusercontent.com/25692596/118511245-56b60180-b74f-11eb-83f4-8a709d3a326b.png)

I have copied and updated the values to config.php from config.ini. Now I just have to remove config.ini file. Is this correct?
Will this solve the error which I am getting in Unity Console as well?

**Comment by dclgamingtr** [comment]
This is not for the error you got. It prevents your data from being seen by everyone. Delete the config.ini file.

**Comment by pandey623** [comment]
deleted config.ini file.
Please help me fixing the error.

**Comment by dclgamingtr** [comment]
Which php version are you using?

**Comment by pandey623** [comment]
![image](https://user-images.githubusercontent.com/25692596/118512878-cb3d7000-b750-11eb-89f7-2ee17549f11e.png)

**Comment by dclgamingtr** [comment]
Change your PHP version to 7.3. Otherwise it will not work.

**Comment by pandey623** [comment]
How and where I can update it?

**Comment by dclgamingtr** [comment]
Are you using Cpanel?

**Comment by pandey623** [comment]
yes

**Comment by dclgamingtr** [comment]
![phpvers2ww](https://user-images.githubusercontent.com/61230304/118515818-6711b080-b73e-11eb-8d46-150568b92896.png)
![phpvers2](https://user-images.githubusercontent.com/61230304/118515820-6842dd80-b73e-11eb-8f89-0cc1b49e793a.png)

**Comment by dclgamingtr** [comment]
Is your problem solved?

**Comment by pandey623** [comment]
I am worried about the side effects if there are any after changing the PHP version? I will update it and check whether the problem is solved or not and update the status here.

**Comment by insthync** [comment]
Try use URL: http://busygamers.com/rpg-php-service-master , No last slash, If you look at the log you will see its URL is wrong 

![Screenshot_421](https://user-images.githubusercontent.com/2697550/118537340-09e62100-b777-11eb-9402-13dc10c93d21.png)

**Comment by pandey623** [comment]
> Try use URL: http://busygamers.com/rpg-php-service-master , No last slash, If you look at the log you will see its URL is wrong
> 
> ![Screenshot_421](https://user-images.githubusercontent.com/2697550/118537340-09e62100-b777-11eb-9402-13dc10c93d21.png)

I have applied this change suggested by @dclgamingtr .
As mentioned by @dclgamingtr I am upgrading to PHP version 7.
I hope this will solve the issue which I reported earlier

**Comment by insthync** [comment]
> Change the name to Config.php instead of config.ini.

You actually can change file permission to not allow to see publicly

![Screenshot_422](https://user-images.githubusercontent.com/2697550/118538047-e374b580-b777-11eb-82fc-5d116d21b42a.png)

**Comment by pandey623** [comment]
> > Now I am getting this error
> > And can you guide me on how to encrypt config.ini page?
> > ![image](https://user-images.githubusercontent.com/25692596/118508820-24a3a000-b74d-11eb-9cdc-40d542c8bce5.png)
> > ![image](https://user-images.githubusercontent.com/25692596/118508858-3127f880-b74d-11eb-8d18-90d49d1328d6.png)
> > ![image](https://user-images.githubusercontent.com/25692596/118508988-4c930380-b74d-11eb-9717-32adb8096042.png)
> 
> Please look into this error as well

Please help me with this issue @insthync

**Comment by pandey623** [comment]
> > Change the name to Config.php instead of config.ini.
> 
> You actually can change file permission to not allow to see publicly
> 
> ![Screenshot_422](https://user-images.githubusercontent.com/2697550/118538047-e374b580-b777-11eb-82fc-5d116d21b42a.png)

ok sure I will keep it in mind

**Comment by pandey623** [comment]
![image](https://user-images.githubusercontent.com/25692596/118542215-55e19780-b770-11eb-9516-5291604f5d15.png)
![image](https://user-images.githubusercontent.com/25692596/118542458-a8bb4f00-b770-11eb-9894-2efba3869eb4.png)
![image](https://user-images.githubusercontent.com/25692596/118542608-d99b8400-b770-11eb-9a6f-630931b1743b.png)

I uploaded files to my other domain where I updated the PHP version to 7.
But still, I am getting these errors.
Please help

**Comment by insthync** [comment]
Try tick these on 
![Screenshot_424](https://user-images.githubusercontent.com/2697550/118584595-8140a280-b7c1-11eb-9674-095c514d0cf3.png)

And set config `use_request_query_action` in `config.ini` to `TRUE`

**Comment by insthync** [comment]
Hey, how is it?

**Comment by pandey623** [comment]
> Hey, how is it?

It is working. Thanks, @insthync for the awesome support
