### ISSUE TITLE
I've installed Apache, PHP, MySQL, but how exactly do I need to deploy the associated game server?

### ISSUE THREAD

**Issue by TankLin2017** [insthync/rpg-php-service#2]
I've installed Apache, PHP, MySQL, but how exactly do I need to deploy the associated game server? Hope the official can make a simple teaching video to facilitate learning.

**Comment by insthync** [comment]
You are never host any PHP web application right?

Because it is very easy, just prepare MySQL database connection info, copy web-service to Apache document folder, and run the MySQL database creation script, it was described in README -> How to setup section.
