### ISSUE TITLE
jsonreaderexception

### ISSUE THREAD

**Issue by cryptotower8** [insthync/rpg-php-service#4]
i recive a error 
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by insthync** [comment]
O_O, please attach full log, you have to enable debugging

![Screenshot_1057](https://user-images.githubusercontent.com/2697550/164961223-97e0acf8-ef16-45e8-97ef-0f295e998c12.png)

Then select result log, copy it and paste here

![Screenshot_1058](https://user-images.githubusercontent.com/2697550/164961621-b2339c91-3c37-438d-a226-4c89d9b23045.png)

**Comment by cryptotower8** [comment]
JsonReaderException: Unexpected character encountered while parsing value: ;. Path '', line 0, position 0.
Newtonsoft.Json.JsonTextReader.ParseValue () (at <bc3985d37b0241b48fc21474b2de25bd>:0)
Newtonsoft.Json.JsonTextReader.Read () (at <bc3985d37b0241b48fc21474b2de25bd>:0)
Newtonsoft.Json.JsonReader.ReadAndMoveToContent () (at <bc3985d37b0241b48fc21474b2de25bd>:0)
Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) (at <bc3985d37b0241b48fc21474b2de25bd>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <bc3985d37b0241b48fc21474b2de25bd>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <bc3985d37b0241b48fc21474b2de25bd>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <bc3985d37b0241b48fc21474b2de25bd>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at <bc3985d37b0241b48fc21474b2de25bd>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at <bc3985d37b0241b48fc21474b2de25bd>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value) (at <bc3985d37b0241b48fc21474b2de25bd>:0)
WebServiceClient+<>c__DisplayClass6_0`1[T].<GetAsDecodedJSON>b__0 (UnityEngine.Networking.UnityWebRequest www) (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:54)
WebServiceClient+<GetRoutine>d__7.MoveNext () (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:106)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <0ee480759f3d481d82ada245dc74f9fd>:0)

**Comment by insthync** [comment]
No, not this I want a JSON value

**Comment by insthync** [comment]
Close  because it has no responding
