### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by crashbruns** [insthync/rpg-php-service#5]
I export my gamedata and now i receve http 1.1 500 internal server error,when i try to log in
![Capturar](https://user-images.githubusercontent.com/104623132/166077052-224f2e71-a32d-4b89-93a4-9f674fe298d4.JPG)

**Comment by crashbruns** [comment]
> I export my gamedata and now i receve http 1.1 500 internal server error

Only variables should be passed by reference

**Comment by crashbruns** [comment]
@insthync

**Comment by insthync** [comment]
![Screenshot_1064](https://user-images.githubusercontent.com/2697550/166183211-d7ba819f-ebe3-466c-8423-82277093ea3c.png)

How about this settings?

**Comment by crashbruns** [comment]
i'm ussing 2020.3.25f1 unity
![unity](https://user-images.githubusercontent.com/104623132/166340652-72f45ba3-fe94-41d4-9b23-c0241d428091.JPG)

**Comment by insthync** [comment]
Can you attach the exported game database ?

**Comment by crashbruns** [comment]
[GameData.zip](https://github.com/insthync/rpg-php-service/files/8606709/GameData.zip)

**Comment by insthync** [comment]
May I try on your device by AnyDesk?

**Comment by crashbruns** [comment]
Of corse,when?

**Comment by crashbruns** [comment]
When i import to db,ALL tablet ia empty

**Comment by crashbruns** [comment]
what version of unity do you use? is it android or pc?

**Comment by insthync** [comment]
Error is occurring at server-side, so any version of Unity won't fix it.

**Comment by insthync** [comment]
I am currently available, you can tell me your AnyDesk info now, send it to my email: ittipon.bay@gmail.com
