### ISSUE TITLE
Please implement attendance check on the 7th and attendance check on the 30th.

### ISSUE THREAD

**Issue by SEUNGHWANYOUN** [insthync/rpg-php-service#6]
hi

I'd like to suggest an additional attendance check function.

Thank you.

**Comment by insthync** [comment]
Try 1.21

**Comment by SEUNGHWANYOUN** [comment]
Thank you. I'm currently applying it. I'll let you know if there's a
problem.

2022년 11월 1일 (화) 오전 7:13, Ittipon Teerapruettikulchai <
***@***.***>님이 작성:
